### ISSUE TITLE
Languages for site to be available in.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Arkia-Links-Site#2]
We need to know in which languages site need to be available.

**Comment by talovdat** [comment]
Only hebrew.

בתאריך 13 ביוני 2017 12:47,‏ "Mladen Mijatov" <notifications@github.com>
כתב:

Assigned #2 <https://github.com/Way2CU/Arkia-Links-Site/issues/2> to
@talovdat <https://github.com/talovdat>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Way2CU/Arkia-Links-Site/issues/2#event-1121033595>, or mute
the thread

**Comment by MeanEYE** [comment]
@iliyaM, do notice this!
